# Generated by Django 5.2.6 on 2025-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0003_location_meetup_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="meetup",
            name="participants",
            field=models.ManyToManyField(blank=True, to="meetups.participant"),
        ),
    ]
