# Generated by Django 5.2.6 on 2025-10-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0004_participant_meetup_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="x-dev@x-dev.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_name",
            field=models.CharField(default="x-dev", max_length=200),
            preserve_default=False,
        ),
    ]
