# Generated by Django 5.2.6 on 2025-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default="defaults/no-image.png",
                null=True,
                upload_to="posts/",
            ),
        ),
    ]
